# Generated by Django 3.2 on 2020-12-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('tourist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Tourist ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Last name')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('passport', models.CharField(max_length=15, verbose_name='Passport')),
                ('itn', models.IntegerField(verbose_name='ITN')),
            ],
            options={
                'verbose_name': 'Tourist',
                'verbose_name_plural': 'Tourists',
            },
        ),
    ]
